import createQuery from 'helpers/createQuery'

export const employeesListQuery = createQuery([
  'id',
  'nome',
  'sobrenome',
  'cpf',
  'status',
  'matricula',
  'possui_acesso',
])

export const newEmployeeQuery = createQuery([
  'id',
  'status',
  'matricula',
  'admitido_em',
  'cargo',
  'salario_bruto',
  'cliente',
  'nome',
  'sobrenome',
  'cpf',
  'salario',
  'saldo_devedor',
  'valor_emprestado',
  'margem_disponivel',
  'possui_acesso',
])

export const employeeQuery = createQuery([
  'id',
  'nome',
  'sobrenome',
  'cpf',
  'status',
  'matricula',
  'possui_acesso',
  'admitido_em',
  'cargo',
  'salario_bruto',
  'salario_liquido',
  'comprometimento_cep',
  'comprometimento_outros',
  'inss',
  'irrf',
  'descontos',

  'cliente__pessoa__nascimento',
  'cliente__pessoa__sexo',
  'cliente__pessoa__dependentes',
  'cliente__pessoa__email',
  'cliente__pessoa__telefone_celular',
  'cliente__pessoa__referencia_nome',
  'cliente__pessoa__referencia_parentesco',
  'cliente__pessoa__referencia_telefone',

  'cliente__endereco__cep',
  'cliente__endereco__cidade',
  'cliente__endereco__uf',
  'cliente__endereco__bairro',
  'cliente__endereco__numero',
  'cliente__endereco__complemento',
  'cliente__endereco__logradouro',

  'pagamento__banco',
  'pagamento__agencia',
  'pagamento__agencia_dac',
  'pagamento__conta',
  'pagamento__conta_dac',
  'pagamento__tipo',
])
