apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: centralcreditfinal
build:
  artifacts:
    - image: dcfranco/cc.service.app
      context: services/app
    - image: dcfranco/cc.service.serasa
      context: services/serasa
deploy:
  kubectl:
    manifests:
      - services/app/build/development/database.yaml
      - services/app/build/development/deployment.yaml
      - services/app/build/development/service.yaml
      - services/app/build/development/storage.yaml
      - services/serasa/build/development/database.yaml
      - services/serasa/build/development/deployment.yaml
      - services/serasa/build/development/service.yaml
      - services/serasa/build/development/storage.yaml
profiles:
  - name: travis-ci
    build:
      local:
        push: false
