apiVersion: v1
data:
  default.conf: |
    server {
            listen 80 default_server;
            listen [::]:80 default_server ipv6only=on;

            listen 443 ssl;

            server_name centralcreditapp.com.br;
            ssl_certificate /etc/nginx/ssl/tls.crt;
            ssl_certificate_key /etc/nginx/ssl/tls.key;

            location / {
                    root /usr/share/nginx/html;
                    try_files $uri $uri/ /index.html;
            }
    }
kind: ConfigMap
metadata:
  name: nginxconfigmap