clone:
  git:
    image: plugins/git:next
    pull: true

pipeline:
  test:
    image: node:10.16-alpine
    commands:
      - yarn install
      - yarn test

  deploy-meucreditofolha-prod:
    when:
      branch: master
      event: push
      status: success
    image: node:10.16-alpine
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - REACT_APP_CREDITOR_BASE_URL=https://creditor-api.creditofolha.com/api
      - REACT_APP_BACKEND_SENTRY_CREDITOR_BASE_DSN=https://01c547b851374f4fb771bc2d82053b22@sentry.io/1319865
      - REACT_APP_FRONTEND_SENTRY_CREDITOR_BASE_DSN=https://81afcbadf9b446b6bca4abcaaacd2782@sentry.io/1392313
      - REACT_APP_PUBLIC_URL=https://meu.creditofolha.com
    commands:
      - rm -rf build/ && yarn install && yarn build
      - apk add --update git && mkdir build/__private__ && echo $(git rev-parse --verify HEAD) > build/__private__/version.html
      - apk add --update py-pip && pip install -U awscli
      - aws s3 sync --sse AES256 --delete build s3://meu.creditofolha.com

  deploy-alfa-prod:
    when:
      branch: master
      event: push
      status: success
    image: node:10.16-alpine
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - REACT_APP_CREDITOR_BASE_URL=https://api.alfa.creditor.cloud/api
      - REACT_APP_BACKEND_SENTRY_CREDITOR_BASE_DSN=https://01c547b851374f4fb771bc2d82053b22@sentry.io/1319865
      - REACT_APP_FRONTEND_SENTRY_CREDITOR_BASE_DSN=https://81afcbadf9b446b6bca4abcaaacd2782@sentry.io/1392313
      - REACT_APP_PUBLIC_URL=https://alfa.creditofolha.com
    commands:
      - rm -rf build/ && yarn install && yarn build
      - apk add --update git && mkdir build/__private__ && echo $(git rev-parse --verify HEAD) > build/__private__/version.html
      - apk add --update py-pip && pip install -U awscli
      - aws s3 sync --sse AES256 --delete build s3://alfa.creditofolha.com
