apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: cc-service-serasa
    labels:
      role: cc-service-serasa
  spec:
    type: NodePort
    externalTrafficPolicy: Cluster
    selector:
      role: cc-service-serasa
    ports:
      - port: 3000
        protocol: TCP
        targetPort: 3000
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: cc-service-serasa
  spec:
    selector:
      matchLabels:
        role: cc-service-serasa
    replicas: 2
    template:
      metadata:
        labels:
          role: cc-service-serasa
      spec:
        containers:
          - name: cc-service-serasa
            image: dcfranco/cc.service.serasa:0.0.0
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 3000
                protocol: TCP
            env:
              - name: MONGODB_SERVICE_HOST
                value: mongo
              - name: MONGODB_SERVICE_PORT
                value: "27017"
        restartPolicy: Always
  status: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
