// @flow

export const AUTH_REQUIRED = 'AUTH_REQUIRED'
export const NOAUTH_REQUIRED = 'NOAUTH_REQUIRED'
export const MODULE_REQUIRED = 'MODULE_REQUIRED'
export const RECENTLY_CREATED = 'RECENTLY_CREATED'
export const NO_SELECTED_PROFILE = 'NO_SELECTED_PROFILE'
export const SELECTED_PROFILE = 'SELECTED_PROFILE'
export const USE_TERMS_ACCEPTED = 'USE_TERMS_ACCEPTED'
export const NO_USE_TERMS_ACCEPTED = 'NO_USE_TERMS_ACCEPTED'
export const AUTO_SELECT_PROFILE = 'AUTO_SELECT_PROFILE'

const PERMISSIONS = {
  AUTH_REQUIRED,
  NOAUTH_REQUIRED,
  MODULE_REQUIRED,
  RECENTLY_CREATED,
  NO_SELECTED_PROFILE,
  SELECTED_PROFILE,
  USE_TERMS_ACCEPTED,
  NO_USE_TERMS_ACCEPTED,
  AUTO_SELECT_PROFILE,
}

export type Permission = $Values<typeof PERMISSIONS>
